projects:
  ai-forms-backend:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: ydzmzqm6nncjpc2idxgmo34dom
        codeGenTarget: typescript
        generatedFileName: src/api.graphql.ts
        docsFilePath: src/graphql
        region: ap-southeast-2
        maxDepth: 2
      endpoints:
        prod: >-
          https://v233t5tzhre2zhzqbmpdwqjzpa.appsync-api.ap-southeast-2.amazonaws.com/graphql
