/* tslint:disable */
//  This file was automatically generated and should not be edited.

export type AddPlanTypeInput = {
  name: string,
  cost: number,
  billingTerm: string,
  active: number,
};

export type AddPlanInput = {
  accountId: string,
  planTypeId: string,
  endDate?: string | null,
  active?: number | null,
};

export type AddIntegrationTypeInput = {
  name: string,
  active?: number | null,
};

export type AddIntegrationInput = {
  integrationTypeId: string,
  accountId: string,
  formId: string,
  active?: number | null,
  authType?: string | null,
  auth?: string | null,
  target?: string | null,
  method?: string | null,
};

export type AddFormInput = {
  accountId: string,
  name: string,
  description: string,
  startsAt?: string | null,
  endsAt?: string | null,
  isPaused?: boolean | null,
};

export type AddFormVersionInput = {
  accountId: string,
  formId: string,
  notes?: string | null,
  formData: string,
};

export type UpdatePlanTypeInput = {
  id: string,
  name?: string | null,
  cost?: number | null,
  billingTerm?: string | null,
  active?: number | null,
};

export type UpdatePlanInput = {
  planId: string,
  accountId: string,
  active: number,
  endDate?: string | null,
};

export type UpdateAccountInput = {
  id: string,
  name?: string | null,
};

export enum AddressType {
  BILLING = "BILLING",
  CONTACT = "CONTACT",
}


export type UpdateUserInput = {
  id: string,
  data: UpdateUserInputData,
};

export type UpdateUserInputData = {
  group: string,
  given_name: string,
  family_name: string,
  phone_number?: string | null,
};

export type UpdateIntegrationTypeInput = {
  id: string,
  name: string,
  active?: number | null,
};

export type UpdateIntegrationInput = {
  id: string,
  active?: number | null,
  authType?: string | null,
  auth?: string | null,
  target?: string | null,
  method?: string | null,
};

export type UpdateFormInput = {
  id: string,
  currentVersionId?: string | null,
  name?: string | null,
  description?: string | null,
  startsAt?: string | null,
  endsAt?: string | null,
  isPaused?: boolean | null,
};

export type DeleteFormInput = {
  id: string,
  accountId: string,
};

export type AddFormEntryInput = {
  data: string,
};

export type OffsetLimit = {
  offset?: number | null,
  limit?: number | null,
};

export type AccountFilterInput = {
  name?: StringFilter | null,
  createdAt?: DateFilter | null,
  updatedAt?: DateFilter | null,
  planId?: IntFilter | null,
  active?: IntFilter | null,
  criteria?: Array< AccountFilterInput > | null,
};

export type StringFilter = {
  with?: FilterWith | null,
  expression: StringFilterExpression,
  value?: Array< string > | null,
};

export enum FilterWith {
  AND = "AND",
  OR = "OR",
}


export enum StringFilterExpression {
  ne = "ne",
  eq = "eq",
  contains = "contains",
  notContains = "notContains",
  startsWith = "startsWith",
  isNull = "isNull",
  isNotNull = "isNotNull",
  in = "in",
}


export type DateFilter = {
  with?: FilterWith | null,
  expression: NumericFilterExpression,
  value?: Array< string > | null,
};

export enum NumericFilterExpression {
  in = "in",
  ne = "ne",
  eq = "eq",
  le = "le",
  lt = "lt",
  ge = "ge",
  gt = "gt",
  between = "between",
  notBetween = "notBetween",
  isNull = "isNull",
  isNotNull = "isNotNull",
}


export type IntFilter = {
  with?: FilterWith | null,
  expression: NumericFilterExpression,
  value?: Array< number > | null,
};

export type UserFilterInput = {
  accountId?: StringFilter | null,
  ownerId?: IntFilter | null,
  email?: StringFilter | null,
  userGroup?: StringFilter | null,
  given_name?: StringFilter | null,
  family_name?: StringFilter | null,
  createdAt?: DateFilter | null,
  updatedAt?: DateFilter | null,
  isDeleted?: IntFilter | null,
  criteria?: Array< UserFilterInput > | null,
};

export type PlanFilterInput = {
  accountId?: IntFilter | null,
  ownerId?: IntFilter | null,
  planTypeId?: IntFilter | null,
  lastBillDate?: DateFilter | null,
  createdAt?: DateFilter | null,
  updatedAt?: DateFilter | null,
  startDate?: DateFilter | null,
  endDate?: DateFilter | null,
  criteria?: Array< PlanFilterInput > | null,
};

export type PlanTypeFilterInput = {
  ownerId?: IntFilter | null,
  cost?: FloatFilter | null,
  billingTerm?: StringFilter | null,
  name?: StringFilter | null,
  createdAt?: DateFilter | null,
  updatedAt?: DateFilter | null,
  isDeleted?: IntFilter | null,
  criteria?: Array< PlanTypeFilterInput > | null,
};

export type FloatFilter = {
  with?: FilterWith | null,
  expression: NumericFilterExpression,
  value?: Array< number > | null,
};

export type FormFilterInput = {
  name?: StringFilter | null,
  ownerId?: IntFilter | null,
  accountId?: IntFilter | null,
  createdAt?: DateFilter | null,
  updatedAt?: DateFilter | null,
  startsAt?: DateFilter | null,
  endsAt?: DateFilter | null,
  isPaused?: IntFilter | null,
  isDeleted?: IntFilter | null,
  criteria?: Array< FormFilterInput > | null,
};

export type IntegrationTypeFilterInput = {
  ownerId?: IntFilter | null,
  planTypeId?: IntFilter | null,
  name?: StringFilter | null,
  createdAt?: DateFilter | null,
  updatedAt?: DateFilter | null,
  active?: IntFilter | null,
  criteria?: Array< IntegrationTypeFilterInput > | null,
};

export type IntegrationFilterInput = {
  ownerId?: IntFilter | null,
  accountId?: IntFilter | null,
  formId?: IntFilter | null,
  active?: IntFilter | null,
  isDeleted?: IntFilter | null,
  lastExecuted?: DateFilter | null,
  lastExecutionResult?: IntFilter | null,
  createdAt?: DateFilter | null,
  updatedAt?: DateFilter | null,
  criteria?: Array< IntegrationFilterInput > | null,
};

export type AddPlanTypeMutationVariables = {
  input?: AddPlanTypeInput | null,
};

export type AddPlanTypeMutation = {
  addPlanType:  {
    __typename: "PlanType",
    id: string,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    name: string,
    cost: number,
    active: number,
    billingTerm: string,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
  },
};

export type AddPlanMutationVariables = {
  input?: AddPlanInput | null,
};

export type AddPlanMutation = {
  addPlan:  {
    __typename: "Plan",
    id: string,
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    startDate: string,
    endDate: string | null,
    active: number | null,
    lastBillDate: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    isDeleted: number | null,
  },
};

export type AddIntegrationTypeMutationVariables = {
  input?: AddIntegrationTypeInput | null,
};

export type AddIntegrationTypeMutation = {
  addIntegrationType:  {
    __typename: "IntegrationType",
    id: string,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    name: string,
    active: number,
    createdAt: string | null,
    updatedAt: string | null,
  },
};

export type AddIntegrationMutationVariables = {
  input?: AddIntegrationInput | null,
};

export type AddIntegrationMutation = {
  addIntegration:  {
    __typename: "Integration",
    id: string,
    integrationTypeId: string,
    integrationType:  {
      __typename: "IntegrationType",
      id: string,
      ownerId: string,
      planTypeId: string,
      name: string,
      active: number,
      createdAt: string | null,
      updatedAt: string | null,
    } | null,
    ownerId: string,
    accountId: string,
    formId: string,
    form:  {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    },
    active: number,
    authType: string | null,
    auth: string | null,
    target: string | null,
    method: string | null,
    lastExecuted: string | null,
    lastExecutionResult: number | null,
    lastExecutionResultMessage: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
  },
};

export type AddFormMutationVariables = {
  input: AddFormInput,
};

export type AddFormMutation = {
  addForm:  {
    __typename: "Form",
    id: string,
    ownerId: string,
    name: string,
    description: string,
    versionId: string,
    formData:  {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    createdAt: string,
    updatedAt: string | null,
    startDate: string | null,
    endDate: string | null,
    isPaused: boolean | null,
    isDeleted: boolean | null,
    versions:  Array< {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null > | null,
    integrations:  Array< {
      __typename: "Integration",
      id: string,
      integrationTypeId: string,
      ownerId: string,
      accountId: string,
      formId: string,
      active: number,
      authType: string | null,
      auth: string | null,
      target: string | null,
      method: string | null,
      lastExecuted: string | null,
      lastExecutionResult: number | null,
      lastExecutionResultMessage: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null > | null,
    entries:  Array< {
      __typename: "FormEntry",
      id: string,
      formId: string,
      data: string,
      createdAt: string,
    } | null > | null,
  },
};

export type AddFormVersionMutationVariables = {
  input?: AddFormVersionInput | null,
};

export type AddFormVersionMutation = {
  addFormVersion:  {
    __typename: "Form",
    id: string,
    ownerId: string,
    name: string,
    description: string,
    versionId: string,
    formData:  {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    createdAt: string,
    updatedAt: string | null,
    startDate: string | null,
    endDate: string | null,
    isPaused: boolean | null,
    isDeleted: boolean | null,
    versions:  Array< {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null > | null,
    integrations:  Array< {
      __typename: "Integration",
      id: string,
      integrationTypeId: string,
      ownerId: string,
      accountId: string,
      formId: string,
      active: number,
      authType: string | null,
      auth: string | null,
      target: string | null,
      method: string | null,
      lastExecuted: string | null,
      lastExecutionResult: number | null,
      lastExecutionResultMessage: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null > | null,
    entries:  Array< {
      __typename: "FormEntry",
      id: string,
      formId: string,
      data: string,
      createdAt: string,
    } | null > | null,
  },
};

export type UpdatePlanTypeMutationVariables = {
  input?: UpdatePlanTypeInput | null,
};

export type UpdatePlanTypeMutation = {
  updatePlanType:  {
    __typename: "PlanType",
    id: string,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    name: string,
    cost: number,
    active: number,
    billingTerm: string,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
  },
};

export type UpdatePlanMutationVariables = {
  input?: UpdatePlanInput | null,
};

export type UpdatePlanMutation = {
  updatePlan:  {
    __typename: "Plan",
    id: string,
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    startDate: string,
    endDate: string | null,
    active: number | null,
    lastBillDate: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    isDeleted: number | null,
  },
};

export type UpdateAccountMutationVariables = {
  input?: UpdateAccountInput | null,
};

export type UpdateAccountMutation = {
  updateAccount:  {
    __typename: "Account",
    id: string,
    name: string,
    addresses:  Array< {
      __typename: "Address",
      id: string,
      name: string,
      addressee: string | null,
      addressType: AddressType,
      phone_number: string | null,
      email: string,
      street: string | null,
      city: string | null,
      state: string | null,
      country: string | null,
    } | null > | null,
    website: string | null,
    taxId: string | null,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    plan:  {
      __typename: "Plan",
      id: string,
      accountId: string,
      ownerId: string,
      planTypeId: string,
      startDate: string,
      endDate: string | null,
      active: number | null,
      lastBillDate: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    planId: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    active: number | null,
    numForms: number | null,
    numUsers: number | null,
    users:  Array< {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    } | null > | null,
    forms:  Array< {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    } | null > | null,
  },
};

export type UpdateAccountPlanMutationVariables = {
  input?: AddPlanInput | null,
};

export type UpdateAccountPlanMutation = {
  updateAccountPlan:  {
    __typename: "Account",
    id: string,
    name: string,
    addresses:  Array< {
      __typename: "Address",
      id: string,
      name: string,
      addressee: string | null,
      addressType: AddressType,
      phone_number: string | null,
      email: string,
      street: string | null,
      city: string | null,
      state: string | null,
      country: string | null,
    } | null > | null,
    website: string | null,
    taxId: string | null,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    plan:  {
      __typename: "Plan",
      id: string,
      accountId: string,
      ownerId: string,
      planTypeId: string,
      startDate: string,
      endDate: string | null,
      active: number | null,
      lastBillDate: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    planId: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    active: number | null,
    numForms: number | null,
    numUsers: number | null,
    users:  Array< {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    } | null > | null,
    forms:  Array< {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    } | null > | null,
  },
};

export type UpdateUserMutationVariables = {
  input?: UpdateUserInput | null,
};

export type UpdateUserMutation = {
  updateUser:  {
    __typename: "User",
    id: string,
    ownerId: string,
    accountId: string | null,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    } | null,
    email: string,
    userGroup: string,
    given_name: string,
    family_name: string,
    phone_number: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
    numForms: number | null,
  },
};

export type UpdateIntegrationTypeMutationVariables = {
  input?: UpdateIntegrationTypeInput | null,
};

export type UpdateIntegrationTypeMutation = {
  updateIntegrationType:  {
    __typename: "IntegrationType",
    id: string,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    name: string,
    active: number,
    createdAt: string | null,
    updatedAt: string | null,
  },
};

export type UpdateIntegrationMutationVariables = {
  input?: UpdateIntegrationInput | null,
};

export type UpdateIntegrationMutation = {
  updateIntegration:  {
    __typename: "Integration",
    id: string,
    integrationTypeId: string,
    integrationType:  {
      __typename: "IntegrationType",
      id: string,
      ownerId: string,
      planTypeId: string,
      name: string,
      active: number,
      createdAt: string | null,
      updatedAt: string | null,
    } | null,
    ownerId: string,
    accountId: string,
    formId: string,
    form:  {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    },
    active: number,
    authType: string | null,
    auth: string | null,
    target: string | null,
    method: string | null,
    lastExecuted: string | null,
    lastExecutionResult: number | null,
    lastExecutionResultMessage: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
  },
};

export type UpdateFormMutationVariables = {
  input?: UpdateFormInput | null,
};

export type UpdateFormMutation = {
  updateForm:  {
    __typename: "Form",
    id: string,
    ownerId: string,
    name: string,
    description: string,
    versionId: string,
    formData:  {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    createdAt: string,
    updatedAt: string | null,
    startDate: string | null,
    endDate: string | null,
    isPaused: boolean | null,
    isDeleted: boolean | null,
    versions:  Array< {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null > | null,
    integrations:  Array< {
      __typename: "Integration",
      id: string,
      integrationTypeId: string,
      ownerId: string,
      accountId: string,
      formId: string,
      active: number,
      authType: string | null,
      auth: string | null,
      target: string | null,
      method: string | null,
      lastExecuted: string | null,
      lastExecutionResult: number | null,
      lastExecutionResultMessage: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null > | null,
    entries:  Array< {
      __typename: "FormEntry",
      id: string,
      formId: string,
      data: string,
      createdAt: string,
    } | null > | null,
  },
};

export type DeleteFormMutationVariables = {
  input?: DeleteFormInput | null,
};

export type DeleteFormMutation = {
  deleteForm:  {
    __typename: "Form",
    id: string,
    ownerId: string,
    name: string,
    description: string,
    versionId: string,
    formData:  {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    createdAt: string,
    updatedAt: string | null,
    startDate: string | null,
    endDate: string | null,
    isPaused: boolean | null,
    isDeleted: boolean | null,
    versions:  Array< {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null > | null,
    integrations:  Array< {
      __typename: "Integration",
      id: string,
      integrationTypeId: string,
      ownerId: string,
      accountId: string,
      formId: string,
      active: number,
      authType: string | null,
      auth: string | null,
      target: string | null,
      method: string | null,
      lastExecuted: string | null,
      lastExecutionResult: number | null,
      lastExecutionResultMessage: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null > | null,
    entries:  Array< {
      __typename: "FormEntry",
      id: string,
      formId: string,
      data: string,
      createdAt: string,
    } | null > | null,
  },
};

export type DeletePlanTypeMutationVariables = {
  planTypeId: string,
};

export type DeletePlanTypeMutation = {
  deletePlanType:  {
    __typename: "PlanType",
    id: string,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    name: string,
    cost: number,
    active: number,
    billingTerm: string,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
  },
};

export type DeletePlanMutationVariables = {
  accountId: string,
  planId: string,
};

export type DeletePlanMutation = {
  deletePlan:  {
    __typename: "Plan",
    id: string,
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    startDate: string,
    endDate: string | null,
    active: number | null,
    lastBillDate: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    isDeleted: number | null,
  },
};

export type DeleteAccountMutationVariables = {
  accountId: string,
};

export type DeleteAccountMutation = {
  deleteAccount:  {
    __typename: "Account",
    id: string,
    name: string,
    addresses:  Array< {
      __typename: "Address",
      id: string,
      name: string,
      addressee: string | null,
      addressType: AddressType,
      phone_number: string | null,
      email: string,
      street: string | null,
      city: string | null,
      state: string | null,
      country: string | null,
    } | null > | null,
    website: string | null,
    taxId: string | null,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    plan:  {
      __typename: "Plan",
      id: string,
      accountId: string,
      ownerId: string,
      planTypeId: string,
      startDate: string,
      endDate: string | null,
      active: number | null,
      lastBillDate: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    planId: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    active: number | null,
    numForms: number | null,
    numUsers: number | null,
    users:  Array< {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    } | null > | null,
    forms:  Array< {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    } | null > | null,
  },
};

export type DeleteUserMutationVariables = {
  userId: string,
};

export type DeleteUserMutation = {
  deleteUser:  {
    __typename: "User",
    id: string,
    ownerId: string,
    accountId: string | null,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    } | null,
    email: string,
    userGroup: string,
    given_name: string,
    family_name: string,
    phone_number: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
    numForms: number | null,
  },
};

export type DeleteIntegrationTypeMutationVariables = {
  integrationTypeId: string,
};

export type DeleteIntegrationTypeMutation = {
  deleteIntegrationType:  {
    __typename: "IntegrationType",
    id: string,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    name: string,
    active: number,
    createdAt: string | null,
    updatedAt: string | null,
  },
};

export type DeleteIntegrationMutationVariables = {
  integrationId: string,
};

export type DeleteIntegrationMutation = {
  deleteIntegration:  {
    __typename: "Integration",
    id: string,
    integrationTypeId: string,
    integrationType:  {
      __typename: "IntegrationType",
      id: string,
      ownerId: string,
      planTypeId: string,
      name: string,
      active: number,
      createdAt: string | null,
      updatedAt: string | null,
    } | null,
    ownerId: string,
    accountId: string,
    formId: string,
    form:  {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    },
    active: number,
    authType: string | null,
    auth: string | null,
    target: string | null,
    method: string | null,
    lastExecuted: string | null,
    lastExecutionResult: number | null,
    lastExecutionResultMessage: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
  },
};

export type AddFormEntryMutationVariables = {
  input: AddFormEntryInput,
};

export type AddFormEntryMutation = {
  addFormEntry:  {
    __typename: "FormEntry",
    id: string,
    formId: string,
    form:  {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    },
    data: string,
    createdAt: string,
  },
};

export type GetAccountQueryVariables = {
  accountId: string,
};

export type GetAccountQuery = {
  getAccount:  {
    __typename: "Account",
    id: string,
    name: string,
    addresses:  Array< {
      __typename: "Address",
      id: string,
      name: string,
      addressee: string | null,
      addressType: AddressType,
      phone_number: string | null,
      email: string,
      street: string | null,
      city: string | null,
      state: string | null,
      country: string | null,
    } | null > | null,
    website: string | null,
    taxId: string | null,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    plan:  {
      __typename: "Plan",
      id: string,
      accountId: string,
      ownerId: string,
      planTypeId: string,
      startDate: string,
      endDate: string | null,
      active: number | null,
      lastBillDate: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    planId: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    active: number | null,
    numForms: number | null,
    numUsers: number | null,
    users:  Array< {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    } | null > | null,
    forms:  Array< {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    } | null > | null,
  } | null,
};

export type GetUserQueryVariables = {
  userId: string,
};

export type GetUserQuery = {
  getUser:  {
    __typename: "User",
    id: string,
    ownerId: string,
    accountId: string | null,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    } | null,
    email: string,
    userGroup: string,
    given_name: string,
    family_name: string,
    phone_number: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
    numForms: number | null,
  } | null,
};

export type GetPlanQueryVariables = {
  planId: string,
};

export type GetPlanQuery = {
  getPlan:  {
    __typename: "Plan",
    id: string,
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    startDate: string,
    endDate: string | null,
    active: number | null,
    lastBillDate: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    isDeleted: number | null,
  } | null,
};

export type GetActiveAccountPlanQueryVariables = {
  accountId: string,
};

export type GetActiveAccountPlanQuery = {
  getActiveAccountPlan:  {
    __typename: "Plan",
    id: string,
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    startDate: string,
    endDate: string | null,
    active: number | null,
    lastBillDate: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    isDeleted: number | null,
  } | null,
};

export type GetPlanTypeQueryVariables = {
  planTypeId: string,
};

export type GetPlanTypeQuery = {
  getPlanType:  {
    __typename: "PlanType",
    id: string,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    name: string,
    cost: number,
    active: number,
    billingTerm: string,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
  } | null,
};

export type GetFormQueryVariables = {
  formId: string,
};

export type GetFormQuery = {
  getForm:  {
    __typename: "Form",
    id: string,
    ownerId: string,
    name: string,
    description: string,
    versionId: string,
    formData:  {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    createdAt: string,
    updatedAt: string | null,
    startDate: string | null,
    endDate: string | null,
    isPaused: boolean | null,
    isDeleted: boolean | null,
    versions:  Array< {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null > | null,
    integrations:  Array< {
      __typename: "Integration",
      id: string,
      integrationTypeId: string,
      ownerId: string,
      accountId: string,
      formId: string,
      active: number,
      authType: string | null,
      auth: string | null,
      target: string | null,
      method: string | null,
      lastExecuted: string | null,
      lastExecutionResult: number | null,
      lastExecutionResultMessage: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null > | null,
    entries:  Array< {
      __typename: "FormEntry",
      id: string,
      formId: string,
      data: string,
      createdAt: string,
    } | null > | null,
  } | null,
};

export type GetIntegrationTypeQueryVariables = {
  integrationTypeId: string,
};

export type GetIntegrationTypeQuery = {
  getIntegrationType:  {
    __typename: "IntegrationType",
    id: string,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    name: string,
    active: number,
    createdAt: string | null,
    updatedAt: string | null,
  } | null,
};

export type GetIntegrationQueryVariables = {
  integrationId: string,
};

export type GetIntegrationQuery = {
  getIntegration:  {
    __typename: "Integration",
    id: string,
    integrationTypeId: string,
    integrationType:  {
      __typename: "IntegrationType",
      id: string,
      ownerId: string,
      planTypeId: string,
      name: string,
      active: number,
      createdAt: string | null,
      updatedAt: string | null,
    } | null,
    ownerId: string,
    accountId: string,
    formId: string,
    form:  {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    },
    active: number,
    authType: string | null,
    auth: string | null,
    target: string | null,
    method: string | null,
    lastExecuted: string | null,
    lastExecutionResult: number | null,
    lastExecutionResultMessage: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
  } | null,
};

export type GetFormEntryQueryVariables = {
  formEntryId: string,
};

export type GetFormEntryQuery = {
  getFormEntry:  {
    __typename: "FormEntry",
    id: string,
    formId: string,
    form:  {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    },
    data: string,
    createdAt: string,
  } | null,
};

export type ListAccountsQueryVariables = {
  offsetLimit?: OffsetLimit | null,
  filter?: AccountFilterInput | null,
};

export type ListAccountsQuery = {
  listAccounts:  Array< {
    __typename: "Account",
    id: string,
    name: string,
    addresses:  Array< {
      __typename: "Address",
      id: string,
      name: string,
      addressee: string | null,
      addressType: AddressType,
      phone_number: string | null,
      email: string,
      street: string | null,
      city: string | null,
      state: string | null,
      country: string | null,
    } | null > | null,
    website: string | null,
    taxId: string | null,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    plan:  {
      __typename: "Plan",
      id: string,
      accountId: string,
      ownerId: string,
      planTypeId: string,
      startDate: string,
      endDate: string | null,
      active: number | null,
      lastBillDate: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    planId: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    active: number | null,
    numForms: number | null,
    numUsers: number | null,
    users:  Array< {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    } | null > | null,
    forms:  Array< {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    } | null > | null,
  } | null > | null,
};

export type ListUsersQueryVariables = {
  offsetLimit?: OffsetLimit | null,
  filter?: UserFilterInput | null,
};

export type ListUsersQuery = {
  listUsers:  Array< {
    __typename: "User",
    id: string,
    ownerId: string,
    accountId: string | null,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    } | null,
    email: string,
    userGroup: string,
    given_name: string,
    family_name: string,
    phone_number: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
    numForms: number | null,
  } | null > | null,
};

export type ListPlansQueryVariables = {
  offsetLimit?: OffsetLimit | null,
  filter?: PlanFilterInput | null,
};

export type ListPlansQuery = {
  listPlans:  Array< {
    __typename: "Plan",
    id: string,
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    startDate: string,
    endDate: string | null,
    active: number | null,
    lastBillDate: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    isDeleted: number | null,
  } | null > | null,
};

export type ListPlanTypesQueryVariables = {
  offsetLimit?: OffsetLimit | null,
  filter?: PlanTypeFilterInput | null,
};

export type ListPlanTypesQuery = {
  listPlanTypes:  Array< {
    __typename: "PlanType",
    id: string,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    name: string,
    cost: number,
    active: number,
    billingTerm: string,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
  } | null > | null,
};

export type ListFormsQueryVariables = {
  offsetLimit?: OffsetLimit | null,
  filter?: FormFilterInput | null,
};

export type ListFormsQuery = {
  listForms:  Array< {
    __typename: "Form",
    id: string,
    ownerId: string,
    name: string,
    description: string,
    versionId: string,
    formData:  {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    accountId: string,
    account:  {
      __typename: "Account",
      id: string,
      name: string,
      website: string | null,
      taxId: string | null,
      ownerId: string,
      planId: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      active: number | null,
      numForms: number | null,
      numUsers: number | null,
    },
    createdAt: string,
    updatedAt: string | null,
    startDate: string | null,
    endDate: string | null,
    isPaused: boolean | null,
    isDeleted: boolean | null,
    versions:  Array< {
      __typename: "FormVersion",
      id: string,
      formId: string,
      ownerId: string,
      createdAt: string | null,
      notes: string | null,
      formData: string | null,
    } | null > | null,
    integrations:  Array< {
      __typename: "Integration",
      id: string,
      integrationTypeId: string,
      ownerId: string,
      accountId: string,
      formId: string,
      active: number,
      authType: string | null,
      auth: string | null,
      target: string | null,
      method: string | null,
      lastExecuted: string | null,
      lastExecutionResult: number | null,
      lastExecutionResultMessage: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null > | null,
    entries:  Array< {
      __typename: "FormEntry",
      id: string,
      formId: string,
      data: string,
      createdAt: string,
    } | null > | null,
  } | null > | null,
};

export type ListIntegrationTypesQueryVariables = {
  offsetLimit?: OffsetLimit | null,
  filter?: IntegrationTypeFilterInput | null,
};

export type ListIntegrationTypesQuery = {
  listIntegrationTypes:  Array< {
    __typename: "IntegrationType",
    id: string,
    ownerId: string,
    ownedBy:  {
      __typename: "User",
      id: string,
      ownerId: string,
      accountId: string | null,
      email: string,
      userGroup: string,
      given_name: string,
      family_name: string,
      phone_number: string | null,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
      numForms: number | null,
    },
    planTypeId: string,
    planType:  {
      __typename: "PlanType",
      id: string,
      ownerId: string,
      name: string,
      cost: number,
      active: number,
      billingTerm: string,
      createdAt: string | null,
      updatedAt: string | null,
      isDeleted: number | null,
    } | null,
    name: string,
    active: number,
    createdAt: string | null,
    updatedAt: string | null,
  } | null > | null,
};

export type ListIntegrationsQueryVariables = {
  offsetLimit?: OffsetLimit | null,
  filter?: IntegrationFilterInput | null,
};

export type ListIntegrationsQuery = {
  listIntegrations:  Array< {
    __typename: "Integration",
    id: string,
    integrationTypeId: string,
    integrationType:  {
      __typename: "IntegrationType",
      id: string,
      ownerId: string,
      planTypeId: string,
      name: string,
      active: number,
      createdAt: string | null,
      updatedAt: string | null,
    } | null,
    ownerId: string,
    accountId: string,
    formId: string,
    form:  {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    },
    active: number,
    authType: string | null,
    auth: string | null,
    target: string | null,
    method: string | null,
    lastExecuted: string | null,
    lastExecutionResult: number | null,
    lastExecutionResultMessage: string | null,
    createdAt: string | null,
    updatedAt: string | null,
    isDeleted: number | null,
  } | null > | null,
};

export type ListFormEntriesQueryVariables = {
  offsetLimit?: OffsetLimit | null,
  formId: string,
};

export type ListFormEntriesQuery = {
  listFormEntries:  Array< {
    __typename: "FormEntry",
    id: string,
    formId: string,
    form:  {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    },
    data: string,
    createdAt: string,
  } | null > | null,
};

export type ListFormEntriesByTimeQueryVariables = {
  offsetLimit?: OffsetLimit | null,
  formId: string,
  timestampPrefix: string,
};

export type ListFormEntriesByTimeQuery = {
  listFormEntriesByTime:  Array< {
    __typename: "FormEntry",
    id: string,
    formId: string,
    form:  {
      __typename: "Form",
      id: string,
      ownerId: string,
      name: string,
      description: string,
      versionId: string,
      accountId: string,
      createdAt: string,
      updatedAt: string | null,
      startDate: string | null,
      endDate: string | null,
      isPaused: boolean | null,
      isDeleted: boolean | null,
    },
    data: string,
    createdAt: string,
  } | null > | null,
};
